<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lens;

class LensSeeder extends Seeder
{
    public function run(): void
    {

        Lens::truncate();

        $models =
            [
                [
                    'model' => 'Canon CN-E 70-200mm T4.4 L IS KAS S',
                    'price' => 5100,
                    'description' => 'The Canon CN-E 70-200mm T4.4 L IS KAS S is a high-performance cinema zoom lens designed for professional filmmakers. Featuring a short EF mount, it offers a constant T4.4 aperture, exceptional image stabilization, and a versatile focal range, making it ideal for capturing high-quality cinematic shots with precise control over focus and zoom.',
                    'photo' => 'photos/canonLens/canonCN70200.webp',
                    'specifications' => json_encode([
                        "Mount" => "EF",
                        "Maximum Aperture" => "T4.4 (constant)",
                        "Focal Length" => "70-200mm (Zoom)",
                        "Image Stabilization" => "Yes, 4-stop optical image stabilization",
                        "Optical Construction" => "17 elements in 12 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "1.2m",
                        "FilterSize" => "82mm",
                        "Focus System" => "Internal focus system with smooth, silent operation",
                        "Zoom Control" => "Precise and smooth zooming mechanism for cinematic use",
                        "Weight" => "1400g",
                        "Length" => "198.7mm",
                    ]),
                    'type' => 'Cinematic',
                ],
                [
                    'model' => 'Canon CN-E 70-200mm T4.4 L IS KAS S',
                    'price' => 4700,
                    'description' => 'The Canon CN-E 18-80mm T4.4 L IS KAS S is a versatile cinema zoom lens designed for professional video production. Featuring a constant T4.4 aperture, it offers excellent image stabilization and a wide focal range from 18mm to 80mm, making it ideal for capturing high-quality cinematic footage with smooth, precise control over focus and zoom.',
                    'photo' => 'photos/canonLens/canonCN1880.webp',
                    'specifications' => json_encode([
                        "Mount" => "EF",
                        "Maximum Aperture" => "T4.4 (constant)",
                        "Focal Length" => "18-80mm (Zoom)",
                        "Image Stabilization" => "Yes, 4-stop optical image stabilization",
                        "Optical Construction" => "19 elements in 14 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.4m",
                        "FilterSize" => "77mm",
                        "Focus System" => "Internal focus system with smooth, silent operation",
                        "Zoom Control" => "Precise and smooth zooming mechanism for cinematic use",
                        "Weight" => "1100g",
                        "Length" => "173.5mm",
                    ]),
                    'type' => 'Cinematic',
                ],
                [
                    'model' => 'Canon CN-E50mm T1.3 L F',
                    'price' => 4500,
                    'description' => 'The Canon CN-E 50mm T1.3 L F is a professional cinema lens designed for high-quality video production. Featuring a fast T1.3 aperture, it delivers exceptional low-light performance and shallow depth of field, ideal for cinematic shots with rich detail and smooth focus transitions. The lens is built with robust construction and a precise focus system for filmmakers.',
                    'photo' => 'photos/canonLens/canonCN50.webp',
                    'specifications' => json_encode([
                        "Mount" => "EF",
                        "Maximum Aperture" => "T1.3 (constant)",
                        "Focal Length" => "50mm",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "9 elements in 7 groups",
                        "Diaphragm Blades" => "11",
                        "Minimum Focus Distance" => "0.45m",
                        "FilterSize" => "77mm",
                        "Focus System" => "Internal focus system with smooth, precise operation",
                        "Zoom Control" => "N/A (prime lens)",
                        "Weight" => "650g",
                        "Length" => "98.5mm",
                    ]),
                    'type' => 'Cinematic',
                ],
                [
                    'model' => 'Sony 28-135mm F4 OSS G FE PZ Super35mm',
                    'price' => 2500,
                    'description' => 'The Sony 28-135mm F4 OSS G FE PZ Super35mm is a versatile cinema lens designed for Super35mm and APS-C sensor cameras. It features a constant F4 aperture, power zoom, and Optical SteadyShot (OSS) for smooth and stable video recording. Ideal for filmmakers, it provides high-quality optics, silent operation, and precise control over zoom and focus.',
                    'photo' => 'photos/sonyLens/sony28135.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "F4 (constant)",
                        "Focal Length" => "28-135mm (Zoom)",
                        "Image Stabilization" => "Yes, Optical SteadyShot (OSS)",
                        "Optical Construction" => "18 elements in 12 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.95m",
                        "FilterSize" => "82mm",
                        "Focus System" => "Internal focus with power zoom for smooth, silent operation",
                        "Zoom Control" => "Motorized power zoom with smooth, precise control",
                        "Weight" => "1050g",
                        "Length" => "127.5mm",
                    ]),
                    'type' => 'Cinematic',
                ],
                [
                    'model' => 'Sony 18-110mm F4 OSS G PZ Super35mm',
                    'price' => 3900,
                    'description' => 'The Sony 18-110mm F4 OSS G PZ Super35mm is a professional cinema lens designed for Super35mm and APS-C sensor cameras. It features a constant F4 aperture, power zoom, and Optical SteadyShot (OSS) for smooth and stable footage. With a versatile focal range and precise controls, it’s ideal for filmmakers seeking high-quality, consistent performance.',
                    'photo' => 'photos/sonyLens/sony18110.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "F4 (constant)",
                        "Focal Length" => "18-110mm (Zoom)",
                        "Image Stabilization" => "Yes, Optical SteadyShot (OSS)",
                        "Optical Construction" => "17 elements in 13 groups",
                        "Diaphragm Blades" => "7",
                        "Minimum Focus Distance" => "0.95m",
                        "FilterSize" => "95mm",
                        "Focus System" => "Internal focus with power zoom for smooth, silent operation",
                        "Zoom Control" => "Motorized power zoom with smooth, precise control",
                        "Weight" => "1250g",
                        "Length" => "135mm"
                    ]),
                    'type' => 'Cinematic',
                ],
                [
                    'model' => 'Canon EF 24-70mm f/2.8L II USM',
                    'price' => 2200,
                    'description' => 'The Canon EF 24-70mm f/2.8L II USM is a high-performance standard zoom lens for DSLR cameras, offering a versatile focal range from wide-angle to short telephoto. With a fast constant f/2.8 aperture, it delivers exceptional image quality, sharpness, and low-light performance, making it ideal for both professional photography and videography.',
                    'photo' => 'photos/canonLens/canonEF2470.webp',
                    'specifications' => json_encode([
                        "Mount" => "EF",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "24-70mm (Zoom)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "18 elements in 13 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.38m",
                        "FilterSize" => "82mm",
                        "Focus System" => "Ultrasonic Motor (USM) for fast, silent focusing",
                        "Zoom Control" => "Manual zoom with precise control",
                        "Weight" => "805g",
                        "Length" => "113mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Canon EF 50mm Obiectiv F1.4 USM',
                    'price' => 400,
                    'description' => 'The Canon EF 50mm f/1.4 USM is a prime lens designed for DSLR cameras, offering exceptional image quality with a wide f/1.4 aperture for beautiful background blur and excellent low-light performance. Its fast and quiet autofocus, combined with its compact design, makes it ideal for portraits, street photography, and general use.',
                    'photo' => 'photos/canonLens/canonEF50.webp',
                    'specifications' => json_encode([
                        "Mount" => "EF",
                        "Maximum Aperture" => "f/1.4 (constant)",
                        "Focal Length" => "50mm",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "8 elements in 6 groups",
                        "Diaphragm Blades" => "8",
                        "Minimum Focus Distance" => "0.45m",
                        "FilterSize" => "58mm",
                        "Focus System" => "Ultrasonic Motor (USM) for fast and quiet autofocus",
                        "Zoom Control" => "N/A (prime lens)",
                        "Weight" => "290g",
                        "Length" => "74.2mm"
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Canon EF 70-200mm F4 L IS II USM',
                    'price' => 1700,
                    'description' => 'The Canon EF 70-200mm f/4L IS II USM is a professional-grade telephoto zoom lens, offering exceptional image quality and sharpness. With a constant f/4 aperture and advanced image stabilization, it delivers excellent performance for sports, wildlife, and portrait photography, while maintaining a compact and lightweight design.',
                    'photo' => 'photos/canonLens/canonEF70200.webp',
                    'specifications' => json_encode([
                        "Mount" => "EF",
                        "Maximum Aperture" => "f/4 (constant)",
                        "Focal Length" => "70-200mm (Zoom)",
                        "Image Stabilization" => "Yes, 5-stop optical image stabilization",
                        "Optical Construction" => "20 elements in 15 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "1.2m",
                        "FilterSize" => "72mm",
                        "Focus System" => "Internal focus system with Ultrasonic Motor (USM) for fast, quiet operation",
                        "Zoom Control" => "Manual zoom with smooth and precise control",
                        "Weight" => "780g",
                        "Length" => "176mm"
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Nikon 20mm f/1.8G ED AF-S Nikkor',
                    'price' => 800,
                    'description' => 'The Nikon 20mm f/1.8G ED AF-S Nikkor is a fast, wide-angle prime lens designed for DSLR cameras. With its f/1.8 aperture, it delivers sharp, high-quality images with beautiful background blur and excellent low-light performance. Its lightweight and compact design make it ideal for landscapes, architecture, and astrophotography.',
                    'photo' => 'photos/nikonLens/nikon20.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/1.8 (constant)",
                        "Focal Length" => "20mm",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "11 elements in 9 groups",
                        "Diaphragm Blades" => "7",
                        "Minimum Focus Distance" => "0.2m",
                        "FilterSize" => "77mm",
                        "Focus System" => "Silent Wave Motor (SWM) for fast and quiet autofocus",
                        "Zoom Control" => "N/A (prime lens)",
                        "Weight" => "355g",
                        "Length" => "83mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Nikon AF-S 200-500mm F5.6E ED VR',
                    'price' => 1500,
                    'description' => 'The Nikon AF-S 200-500mm f/5.6E ED VR is a versatile telephoto zoom lens designed for DSLR cameras, offering a long focal range perfect for wildlife, sports, and action photography. With Vibration Reduction (VR) technology, it ensures stable, sharp images even at long distances, while its constant f/5.6 aperture provides consistent performance throughout the zoom range.',
                    'photo' => 'photos/nikonLens/nikonAF200500.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/5.6 (constant)",
                        "Focal Length" => "200-500mm (Zoom)",
                        "Image Stabilization" => "Yes, Vibration Reduction (VR)",
                        "Optical Construction" => "19 elements in 12 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "2.2m",
                        "FilterSize" => "95mm",
                        "Focus System" => "Silent Wave Motor (SWM) for fast and quiet autofocus",
                        "Zoom Control" => "Manual zoom with smooth and precise control",
                        "Weight" => "2300g",
                        "Length" => "267mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Nikon 24-70mm F2.8 AF-S ED VR',
                    'price' => 1800,
                    'description' => 'The Nikon 24-70mm f/2.8 AF-S ED VR is a high-performance standard zoom lens designed for DSLR cameras. With a constant f/2.8 aperture and Vibration Reduction (VR) technology, it delivers sharp, stable images in various lighting conditions, making it ideal for portrait, landscape, and event photography. The lens offers excellent image quality, fast autofocus, and a durable, weather-sealed design.',
                    'photo' => 'photos/nikonLens/nikon2470.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "24-70mm (Zoom)",
                        "Image Stabilization" => "Yes, Vibration Reduction (VR)",
                        "Optical Construction" => "17 elements in 13 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.38m",
                        "FilterSize" => "77mm",
                        "Focus System" => "Silent Wave Motor (SWM) for fast and quiet autofocus",
                        "Zoom Control" => "Manual zoom with smooth and precise control",
                        "Weight" => "1070g",
                        "Length" => "163.5mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Sigma 18-35mm F1.8 HSM Art',
                    'price' => 700,
                    'description' => 'The Sigma 18-35mm F1.8 HSM Art is a wide-angle zoom lens designed for DSLR cameras with a Canon EF-S mount. It features a fast constant f/1.8 aperture, providing excellent low-light performance and stunning background blur. Known for its sharpness and image quality, it is ideal for both photography and videography, especially for landscapes and creative portraits.',
                    'photo' => 'photos/sigmaLens/sigma1835.webp',
                    'specifications' => json_encode([
                        "Mount" => "Canon EF-S",
                        "Maximum Aperture" => "f/1.8 (constant)",
                        "Focal Length" => "18-35mm (Zoom)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "17 elements in 12 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.28m",
                        "FilterSize" => "72mm",
                        "Focus System" => "Hyper Sonic Motor (HSM) for fast and quiet autofocus",
                        "Zoom Control" => "Manual zoom with smooth, precise control",
                        "Weight" => "810g",
                        "Length" => "121.4mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Sigma 35mm F1.4 DG HSM',
                    'price' => 850,
                    'description' => 'The Sigma 35mm f/1.4 DG HSM is a fast prime lens designed for DSLR cameras with a Nikon FX mount. With its wide f/1.4 aperture, it delivers exceptional low-light performance and beautiful background blur. The lens offers superb sharpness and clarity, making it ideal for portraits, street photography, and landscapes.',
                    'photo' => 'photos/sigmaLens/sigma35.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/1.4 (constant)",
                        "Focal Length" => "35mm",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "13 elements in 11 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.30m",
                        "FilterSize" => "67mm",
                        "Focus System" => "Hyper Sonic Motor (HSM) for fast and quiet autofocus",
                        "Zoom Control" => "N/A (prime lens)",
                        "Weight" => "665g",
                        "Length" => "94mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Sigma 85mm F1.4 DG HSM',
                    'price' => 1100,
                    'description' => 'The Sigma 85mm f/1.4 DG HSM is a fast prime lens designed for DSLR cameras with a Nikon FX mount. With its wide f/1.4 aperture, it excels in low-light conditions and creates stunning background blur, making it perfect for portrait and wedding photography. The lens delivers exceptional sharpness and bokeh, providing professional-level image quality.',
                    'photo' => 'photos/sigmaLens/sigma85.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/1.4 (constant)",
                        "Focal Length" => "85mm",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "14 elements in 12 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.85m",
                        "FilterSize" => "86mm",
                        "Focus System" => "Hyper Sonic Motor (HSM) for fast and quiet autofocus",
                        "Zoom Control" => "N/A (prime lens)",
                        "Weight" => "1130g",
                        "Length" => "94mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Tamron 100-400mm F4.5-6.3 Di VC USD',
                    'price' => 800,
                    'description' => 'The Tamron 100-400mm f/4.5-6.3 Di VC USD is a versatile telephoto zoom lens designed for DSLR cameras with a Canon EF mount. It offers a wide focal range, making it ideal for wildlife, sports, and nature photography. The lens features Vibration Compensation (VC) for stability and fast autofocus, providing sharp images even at long distances.',
                    'photo' => 'photos/tamronLens/tamron10400.webp',
                    'specifications' => json_encode([
                        "Mount" => "Canon EF",
                        "Maximum Aperture" => "f/4.5-6.3 (variable)",
                        "Focal Length" => "100-400mm (Zoom)",
                        "Image Stabilization" => "Yes, Vibration Compensation (VC)",
                        "Optical Construction" => "16 elements in 11 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "1.5m",
                        "FilterSize" => "72mm",
                        "Focus System" => "Ultrasonic Silent Drive (USD) for fast and quiet autofocus",
                        "Zoom Control" => "Smooth and precise zooming mechanism",
                        "Weight" => "1115g",
                        "Length" => "182.7mm"
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Tamron 150-600mm F/5-6.3 SP VC USD G2 Nikon',
                    'price' => 1200,
                    'description' => 'The Tamron 150-600mm f/5-6.3 SP VC USD G2 is a powerful telephoto zoom lens designed for Nikon DSLR cameras. It offers an impressive focal range, making it ideal for wildlife, sports, and nature photography. Equipped with Vibration Compensation (VC) and Ultrasonic Silent Drive (USD) for fast and quiet autofocus, it ensures sharp and stable images even at long focal lengths.',
                    'photo' => 'photos/tamronLens/tamron150600.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/5-6.3 (variable)",
                        "Focal Length" => "150-600mm (Zoom)",
                        "Image Stabilization" => "Yes, Vibration Compensation (VC)",
                        "Optical Construction" => "21 elements in 13 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "2.2m",
                        "FilterSize" => "95mm",
                        "Focus System" => "Ultrasonic Silent Drive (USD) for fast and quiet autofocus",
                        "Zoom Control" => "Precise and smooth zoom mechanism",
                        "Weight" => "2010g",
                        "Length" => "260.2mm"
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Tamron 100-400mm F4.5-6.3 Di VC USD',
                    'price' => 820,
                    'description' => 'The Tamron 100-400mm f/4.5-6.3 Di VC USD is a versatile telephoto zoom lens for Nikon DSLR cameras, offering an extended focal range perfect for wildlife, sports, and nature photography. It features Vibration Compensation (VC) for stable shooting and fast, silent autofocus with the Ultrasonic Silent Drive (USD) for precise performance. This lens combines powerful zoom capabilities with excellent image quality.',
                    'photo' => 'photos/tamronLens/tamron10400Nikon.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon F",
                        "Maximum Aperture" => "f/4.5-6.3 (variable)",
                        "Focal Length" => "100-400mm (Zoom)",
                        "Image Stabilization" => "Yes, Vibration Compensation (VC)",
                        "Optical Construction" => "16 elements in 11 groups",
                        "Diaphragm Blades" => "7",
                        "Minimum Focus Distance" => "1.5m",
                        "Filter Size" => "67mm",
                        "Focus System" => "Ultrasonic Silent Drive (USD) for fast and quiet autofocus",
                        "Zoom Control" => "Precise and smooth zooming mechanism",
                        "Weight" => "1115g",
                        "Length" => "182.7mm",
                    ]),
                    'type' => 'DSLR',
                ],
                [
                    'model' => 'Canon RF 24-70mm F2.8 L IS USM',
                    'price' => 2500,
                    'description' => "The Canon RF 24-70mm f/2.8 L IS USM is a high-performance standard zoom lens for Canon's mirrorless cameras. It offers a versatile focal range, constant f/2.8 aperture, and built-in image stabilization, making it ideal for a wide variety of photography styles, from portraits to landscapes. The lens also features fast and silent autofocus, ensuring excellent results in both stills and video.",
                    'photo' => 'photos/canonLens/canonRF2470.webp',
                    'specifications' => json_encode([
                        "Mount" => "RF",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "24-70mm (Zoom)",
                        "Image Stabilization" => "Yes, 5-stop optical image stabilization",
                        "Optical Construction" => "21 elements in 15 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.21m",
                        "Filter Size" => "82mm",
                        "Focus System" => "Dual Nano USM",
                        "Zoom Control" => "Precise and smooth zooming mechanism",
                        "Weight" => "900g",
                        "Length" => "136.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Canon RF 70-200mm F2.8 L IS USM',
                    'price' => 3000,
                    'description' => "The Canon RF 70-200mm f/2.8 L IS USM is a high-performance telephoto zoom lens designed for Canon's mirrorless cameras. It offers a fast constant aperture of f/2.8, along with exceptional image quality and 5-stop image stabilization for clear, sharp shots. Ideal for both photography and videography, it features a compact design and advanced focusing technology.",
                    'photo' => 'photos/canonLens/canonRF70200.webp',
                    'specifications' => json_encode([
                        "Mount" => "RF",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "24-70mm (Zoom)",
                        "Image Stabilization" => "Yes, 5-stop optical image stabilization",
                        "Optical Construction" => "21 elements in 15 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.21m",
                        "Filter Size" => "82mm",
                        "Focus System" => "Dual Nano USM",
                        "Zoom Control" => "Precise and smooth zooming mechanism",
                        "Weight" => "900g",
                        "Length" => "136.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Fujifilm XF 16-50mm F2.8-4.8 R LM WR',
                    'price' => 900,
                    'description' => "The Fujifilm XF 16-50mm F2.8-4.8 R LM WR is a versatile mirrorless lens designed for Fujifilm X-series cameras. With a wide focal length range, it offers both portability and excellent image quality, featuring a fast autofocus system and weather-resistant design for challenging shooting conditions.",
                    'photo' => 'photos/fujifilmLens/fujifilmXF1650.webp',
                    'specifications' => json_encode([
                        "Mount" => "RF",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "24-70mm (Zoom)",
                        "Image Stabilization" => "Yes, 5-stop optical image stabilization",
                        "Optical Construction" => "21 elements in 15 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.21m",
                        "Filter Size" => "82mm",
                        "Focus System" => "Dual Nano USM",
                        "Zoom Control" => "Precise and smooth zooming mechanism",
                        "Weight" => "900g",
                        "Length" => "136.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Fujifilm 60mm F2.4 macro 1:1 R XF',
                    'price' => 700,
                    'description' => "The Fujifilm 60mm F2.4 Macro 1:1 XF lens is a versatile macro lens designed for close-up photography, offering a 1:1 magnification ratio. It provides sharp image quality with a bright f/2.4 aperture, making it ideal for capturing intricate details with stunning clarity. Its compact size and lightweight design make it an excellent choice for both studio and outdoor macro photography.",
                    'photo' => 'photos/fujifilmLens/fujifilmX60.webp',
                    'specifications' => json_encode([
                        "Mount" => "XF",
                        "Maximum Aperture" => "f/2.4",
                        "Focal Length" => "60mm (Prime)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "10 elements in 8 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.26m",
                        "Filter Size" => "62mm",
                        "Focus System" => "Internal focusing system",
                        "Zoom Control" => "N/A",
                        "Weight" => "335g",
                        "Length" => "73.9mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Nikon Z 35mm f/1.8 S',
                    'price' => 750,
                    'description' => "The Nikon Z 35mm f/1.8 S is a prime lens designed for Nikon's mirrorless Z-series cameras. It offers exceptional sharpness, fast and silent autofocus, and a wide f/1.8 aperture, ideal for low-light photography and achieving beautiful background blur. Its compact and lightweight design makes it perfect for everyday use.",
                    'photo' => 'photos/nikonLens/nikonZ35.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon Z",
                        "Maximum Aperture" => "f/1.8",
                        "Focal Length" => "35mm (Prime)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "9 elements in 6 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.3m",
                        "Filter Size" => "52mm",
                        "Focus System" => "Internal focus system with fast and quiet operation",
                        "Weight" => "310g",
                        "Length" => "73.5mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Nikon Z 70-200mm F2.8 VR S',
                    'price' => 2300,
                    'description' => "The Nikon Z 70-200mm f/2.8 VR S is a versatile telephoto zoom lens designed for Nikon Z mirrorless cameras. With its constant f/2.8 aperture and advanced image stabilization, it delivers sharp, high-quality images in various lighting conditions. Ideal for sports, wildlife, and portrait photography, this lens offers fast autofocus and superior optical performance.",
                    'photo' => 'photos/nikonLens/nikonZ70200.webp',
                    'specifications' => json_encode([
                        "Mount" => "Nikon Z",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "70-200mm (Zoom)",
                        "Image Stabilization" => "Yes, 5-stop optical image stabilization",
                        "Optical Construction" => "21 elements in 15 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.50m",
                        "Filter Size" => "77mm",
                        "Focus System" => "Silky Swift VCM (Voice Coil Motor)",
                        "Zoom Control" => "Smooth and precise zooming mechanism",
                        "Weight" => "1,140g",
                        "Length" => "207mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Panasonic 85mm F1.8 (white-box)',
                    'price' => 500,
                    'description' => "The Panasonic 85mm F1.8 L-mount is a prime lens designed for full-frame mirrorless cameras. It offers a bright f/1.8 aperture for excellent low-light performance and a shallow depth of field, ideal for portraits. Its compact, lightweight design ensures mobility while maintaining high-quality image resolution.",
                    'photo' => 'photos/panasonicLens/panasonic85.webp',
                    'specifications' => json_encode([
                        "Mount" => "L-mount",
                        "Maximum Aperture" => "f/1.8",
                        "Focal Length" => "85mm (Prime)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "9 elements in 8 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.8m",
                        "Filter Size" => "67mm",
                        "Focus System" => "Linear AF Motor",
                        "Weight" => "305g",
                        "Length" => "73.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Panasonic Leica DG Vario-Elmarit 12-35mm F2.8 ASPH Power O.I.S.',
                    'price' => 1100,
                    'description' => "The Panasonic Leica DG Vario-Elmarit 12-35mm F2.8 ASPH Power O.I.S. is a versatile zoom lens designed for Micro Four Thirds mirrorless cameras. It offers a constant f/2.8 aperture, ensuring excellent low-light performance and beautiful background blur. The lens also features Optical Image Stabilization for smooth handheld shooting.",
                    'photo' => 'photos/panasonicLens/panasonic1235.webp',
                    'specifications' => json_encode([
                        "Mount" => "Micro Four Thirds",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "12-35mm (Zoom)",
                        "Image Stabilization" => "Yes, Power O.I.S.",
                        "Optical Construction" => "14 elements in 9 groups",
                        "Diaphragm Blades" => "7",
                        "Minimum Focus Distance" => "0.25m",
                        "Filter Size" => "58mm",
                        "Focus System" => "Internal focus system",
                        "Zoom Control" => "Smooth zooming mechanism",
                        "Weight" => "305g",
                        "Length" => "70.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Sigma 16mm F1.4 DN',
                    'price' => 450,
                    'description' => "The Sigma 16mm F1.4 DC DN is a wide-angle prime lens designed for Sony E-mount mirrorless cameras. With a fast f/1.4 aperture, it delivers excellent low-light performance and stunning background blur. Ideal for landscape, street, and vlogging photography, this lens offers sharp image quality and compact design.",
                    'photo' => 'photos/sigmaLens/sigmaDN16.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "f/1.4",
                        "Focal Length" => "16mm (Prime)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "13 elements in 11 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.25m",
                        "Filter Size" => "67mm",
                        "Focus System" => "Stepping Motor (STM)",
                        "Zoom Control" => "N/A (Prime lens)",
                        "Weight" => "405g",
                        "Length" => "92.3mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Sigma 50mm F1.4 II DG DN Art',
                    'price' => 830,
                    'description' => "The Sigma 50mm F1.4 II DG DN Art lens for Sony FE mount offers exceptional image quality with a fast f/1.4 aperture, perfect for both low-light and portrait photography. It features a robust, weather-sealed design and fast, accurate autofocus, making it ideal for both professional and enthusiast photographers seeking a high-performance standard prime lens.",
                    'photo' => 'photos/sigmaLens/sigmaDN50.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony FE",
                        "Maximum Aperture" => "f/1.4 (constant)",
                        "Focal Length" => "50mm (Prime)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "14 elements in 11 groups",
                        "Diaphragm Blades" => "11",
                        "Minimum Focus Distance" => "0.40m",
                        "Filter Size" => "67mm",
                        "Focus System" => "Hyper Sonic Motor (HSM)",
                        "Weight" => "435g",
                        "Length" => "91.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Sony FE 24-70mm F2.8 GM II',
                    'price' => 2400,
                    'description' => "The Sony FE 24-70mm F2.8 GM II is a high-performance standard zoom lens designed for Sony full-frame mirrorless cameras. Offering a fast constant aperture of f/2.8, it delivers exceptional image quality, fast autofocus, and advanced optical features, making it ideal for both photography and videography. The lens is compact, lightweight, and built for professional use in various conditions.",
                    'photo' => 'photos/sonyLens/sonyFE2470.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "24-70mm (Zoom)",
                        "Image Stabilization" => "Yes, 5-stop optical image stabilization",
                        "Optical Construction" => "21 elements in 15 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.21m",
                        "Filter Size" => "82mm",
                        "Focus System" => "Dual Nano USM",
                        "Zoom Control" => "Precise and smooth zooming mechanism",
                        "Weight" => "900g",
                        "Length" => "136.8mm"

                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Sony FE 90mm F2.8 Macro OSS G Obiectiv Foto Mirrorless Montura Sony E',
                    'price' => 1200,
                    'description' => "The Sony FE 90mm F2.8 Macro OSS G lens is a high-performance macro lens designed for Sony E-mount mirrorless cameras. It offers a 1:1 magnification ratio and features Optical SteadyShot (OSS) for stable handheld shooting, even at close distances. With a bright f/2.8 aperture, it excels in low light and provides beautiful bokeh for detailed close-up shots.",
                    'photo' => 'photos/sonyLens/sonyFE90.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "f/2.8",
                        "Focal Length" => "90mm (Prime)",
                        "Image Stabilization" => "Yes, Optical SteadyShot (OSS)",
                        "Optical Construction" => "15 elements in 11 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.28m",
                        "Filter Size" => "62mm",
                        "Focus System" => "Internal Focus",
                        "Zoom Control" => "N/A (Fixed focal length)",
                        "Weight" => "602g",
                        "Length" => "139.5mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Tamron 28-75mm F2.8 Di III VXD G2',
                    'price' => 950,
                    'description' => "The Tamron 28-75mm F2.8 Di III VXD G2 for Sony E-mount is a versatile zoom lens, offering a constant aperture of f/2.8 for excellent low-light performance and beautiful bokeh. With improved autofocus and a lightweight design, it's ideal for both photography and videography, providing sharpness across the zoom range.",
                    'photo' => 'photos/tamronLens/tamronG22875.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "f/2.8 (constant)",
                        "Focal Length" => "28-75mm (Zoom)",
                        "Image Stabilization" => "No",
                        "Optical Construction" => "16 elements in 12 groups",
                        "Diaphragm Blades" => "9",
                        "Minimum Focus Distance" => "0.18m",
                        "Filter Size" => "67mm",
                        "Focus System" => "VXD (Voice-coil eXtreme-torque Drive)",
                        "Zoom Control" => "Smooth zooming mechanism",
                        "Weight" => "540g",
                        "Length" => "117.8mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
                [
                    'model' => 'Tamron 18-300mm F3.5-6.3 Di III-A VC VXD',
                    'price' => 950,
                    'description' => "The Tamron 18-300mm F/3.5-6.3 Di III-A VC VXD is a versatile all-in-one zoom lens designed for Sony E-mount mirrorless cameras. It offers a wide focal length range, from wide-angle to telephoto, making it ideal for travel and everyday photography. Featuring VXD autofocus and VC image stabilization, it ensures sharp and stable shots even in challenging conditions.",
                    'photo' => 'photos/tamronLens/tamron18300.webp',
                    'specifications' => json_encode([
                        "Mount" => "Sony E",
                        "Maximum Aperture" => "f/3.5-6.3",
                        "Focal Length" => "18-300mm (Zoom)",
                        "Image Stabilization" => "Yes, VC (Vibration Compensation)",
                        "Optical Construction" => "16 elements in 12 groups",
                        "Diaphragm Blades" => "7",
                        "Minimum Focus Distance" => "0.15m",
                        "Filter Size" => "67mm",
                        "Focus System" => "VXD (Voice-coil eXtreme-torque Drive)",
                        "Zoom Control" => "Smooth zooming mechanism",
                        "Weight" => "620g",
                        "Length" => "121.4mm"
                    ]),
                    'type' => 'Mirrorless',
                ],
            ];

        foreach ($models as $modelData) {
            Lens::updateOrCreate(
                ['model' => $modelData['model']],
                $modelData
            );
        }
    }
}
